"""empty message

Revision ID: 343b0002cad6
Revises: f26feff4c26f
Create Date: 2018-04-25 22:26:59.617634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343b0002cad6'
down_revision = 'f26feff4c26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Course', sa.Column('course_day', sa.String(length=60), nullable=True))
    op.add_column('Course', sa.Column('course_end_time', sa.Time(), nullable=True))
    op.add_column('Course', sa.Column('course_start_time', sa.Time(), nullable=True))
    op.execute('ALTER TABLE Tuition MODIFY tuition_degree VARCHAR(60) NOT NULL')
    # op.drop_constraint('Tuition_ibfk_1', 'Tuition', type_='foreignkey')
    op.execute('ALTER TABLE Tuition DROP PRIMARY KEY, \
        ADD PRIMARY KEY (tuition_semester, tuition_year, faculty_id, tuition_degree)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Course', 'course_start_time')
    op.drop_column('Course', 'course_end_time')
    op.drop_column('Course', 'course_day')
    # sa.ForeignKeyConstraint(['faculty_id'], ['Faculty.faculty_id'])
    op.execute('ALTER TABLE Tuition DROP PRIMARY KEY, \
        ADD PRIMARY KEY (tuition_semester, tuition_year, faculty_id)')
    op.execute('ALTER TABLE Tuition MODIFY tuition_degree VARCHAR(60)')
    # ### end Alembic commands ###
