"""empty message

Revision ID: 97aac3e0b7d2
Revises: 343b0002cad6
Create Date: 2018-04-28 10:48:21.257831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97aac3e0b7d2'
down_revision = '343b0002cad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Request', sa.Column('random_priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Request', 'random_priority')
   # ### end Alembic commands ###
